volumes:
  data:


services:
  teamspeak:
    # 3.13.7
    image: teamspeak@sha256:6756c50d1a0a7e48db95cf4b38d4c6d59ac0b560bc3b9e986ed069d2c16206f5
    ports:
      - "9987:9987/udp"
    environment:
      TS3SERVER_LICENSE: "accept"
    volumes:
      - "data:/var/ts3server"
    security_opt:
      - "no-new-privileges=true"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512M"

